# Site Settings
title: "Code Log Blog"
description: "Code Log Blog"

# Build Settings
# theme: jekyll-theme-minimal
remote_theme: abhinavs/moonwalk
moonwalk:
  theme: dark
  show_theme_toggle: true
  timezone: America/New_York

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
